#!/bin/bash

# The following symbols (past the first five) are taken from the public headers.
# A list of the latter should be available Makefile.am/libdrm_gsgpuinclude_HEADERS

FUNCS=$($NM -D --format=bsd --defined-only ${1-.libs/libdrm_gsgpu.so} | awk '{print $3}' | while read func; do
( grep -q "^$func$" || echo $func )  <<EOF
__bss_start
_edata
_end
_fini
_init
gsgpu_bo_alloc
gsgpu_bo_cpu_map
gsgpu_bo_cpu_unmap
gsgpu_bo_export
gsgpu_bo_free
gsgpu_bo_import
gsgpu_bo_list_create
gsgpu_bo_list_destroy
gsgpu_bo_list_update
gsgpu_bo_query_info
gsgpu_bo_set_metadata
gsgpu_bo_va_op
gsgpu_bo_va_op_raw
gsgpu_bo_wait_for_idle
gsgpu_create_bo_from_user_mem
gsgpu_cs_chunk_fence_info_to_data
gsgpu_cs_chunk_fence_to_dep
gsgpu_cs_create_semaphore
gsgpu_cs_create_syncobj
gsgpu_cs_create_syncobj2
gsgpu_cs_ctx_create
gsgpu_cs_ctx_create2
gsgpu_cs_ctx_free
gsgpu_cs_destroy_semaphore
gsgpu_cs_destroy_syncobj
gsgpu_cs_export_syncobj
gsgpu_cs_fence_to_handle
gsgpu_cs_import_syncobj
gsgpu_cs_query_fence_status
gsgpu_cs_query_reset_state
gsgpu_query_sw_info
gsgpu_cs_signal_semaphore
gsgpu_cs_submit
gsgpu_cs_submit_raw
gsgpu_cs_syncobj_export_sync_file
gsgpu_cs_syncobj_import_sync_file
gsgpu_cs_syncobj_reset
gsgpu_cs_syncobj_signal
gsgpu_cs_syncobj_wait
gsgpu_cs_wait_fences
gsgpu_cs_wait_semaphore
gsgpu_device_deinitialize
gsgpu_device_initialize
gsgpu_get_marketing_name
gsgpu_hw_sema_get
gsgpu_hw_sema_put
gsgpu_query_buffer_size_alignment
gsgpu_query_crtc_from_id
gsgpu_query_firmware_version
gsgpu_query_gds_info
gsgpu_query_gpu_info
gsgpu_query_heap_info
gsgpu_query_hw_ip_count
gsgpu_query_hw_ip_info
gsgpu_query_info
gsgpu_query_sensor_info
gsgpu_read_mm_registers
gsgpu_va_range_alloc
gsgpu_va_range_free
gsgpu_va_range_query
gsgpu_vm_reserve_vmid
gsgpu_vm_unreserve_vmid
EOF
done)

test ! -n "$FUNCS" || echo $FUNCS
test ! -n "$FUNCS"
