LIBDRM_GSGPU_FILES := \
	gsgpu_asic_id.c \
	gsgpu_bo.c \
	gsgpu_cs.c \
	gsgpu_device.c \
	gsgpu_gpu_info.c \
	gsgpu_internal.h \
	gsgpu_vamgr.c \
	gsgpu_vm.c \
	gsgpu_hw_sema.c \
	util_hash.c \
	util_hash.h \
	util_hash_table.c \
	util_hash_table.h

LIBDRM_GSGPU_H_FILES := \
	gsgpu.h
